wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.11
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723305634.065068
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 23
      - 24
      4: 3.6.9
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
direction:
  desc: null
  value:
  - MAXIMIZE
